qlib:
  provider_uri: ./data/qlib_data_cn
  region: cn

universe: "main_board" # 剔除创业板，科创板，北交所后的股票. default: all

time:
  train: [ "1996-01-01", "2023-12-31" ]
  valid: [ "2024-01-01", "2025-12-31" ]
  test:  [ "2026-01-01", "2026-03-08" ]

features:
  handler: Alpha158
  lookback: 20
  use_valuation: True

model:
  name: lgbm  # default: lstm
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  lr: 0.0005
  epochs: 200
  early_stop: 10
  batch_size: 4096
  n_jobs: 8
  loss: pearson

strategy:
  topk: 30    # default: 30
  n_drop: 5   # default: 5

backtest:
  cost:
    buy: 0.001
    sell: 0.002
